---
title: "Homework 2"
author:
- XXXXXXXX (Only code no name)
- XXXXXXXX (Only code no name)
- XXXXXXXX (Only code no name)
- XXXXXXXX (Only code no name)
- XXXXXXXX (Only code no name)
- XXXXXXXX (Only code no name)
date: ''
output:
  word_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo      = FALSE, 
                      warning   = FALSE,
                      message   = FALSE, 
                      fig.align = "center")
```

# Financial markets I

## Exercise 2

This exercises is taken from: 

**Oliver Blanchard (2017) Macroeconomics (7 Edition)** > Chapter 4 Financial Markets I > Questions and Problems > Exercise 2 

Suppose that the houselhold nominal income for an economy, $Y_t$, is $\$50,000$ billions and the nominal demand for money, $M_t^d$, in this economy is given by:

$$M_t^d = Y_t*(0.2 - 0.8i_t)$$

Where $i_t$ is the nominal interest rate fixed by the central bank.

1. What is the demand for money when the interest rate is $i_t = 0.01 (1\%)$ and $i_t = 0.05 (5\%)$? **(3.5 points)**

2. What will be the impact on the demand of money, $M_t^d$, if the nominal income, $Y_t$, declines by $20\%$? **(3.5 points)**

3. What is the relation between the demand of money, $M_t^d$, and the nominal income, $Y_t$? **(3.5 points)**

4. What is the relation between the demand of money, $M_t^d$, and the nominal interest rate fixed by the central bank, $i_t$? **(3.5 points)**

5. Explain what the central bank should do to the interest rate, $i_t$, if it needs to increase the demand of money, $M_t^d$. **(3.5 points)**

## Data from Colombia in relation to the financial market

### Demand for central bank money

In the appendix of *Chapter 4 Financial Markets I* from the book **Oliver Blanchard (2017) Macroeconomics (7 Edition)** there is an explanation about the demand for central bank money. 

- Enter into the Bank of the Republic (Colombia) using the route:

**http://www.banrep.gov.co/** > Estadísticas > Tasas de interés y sector financiero > 3. Agregados monetarios, encaje y cartera > Agregados monetarios > Descargar y consultar: Efectivo, Base monetaria, M3 y sus componentes - Mensual > Exportar

6. Make a plot of **Efectivo** ($CU_t^d$ in the model), **Reserva Bancaria** ($R_t^d$ in the model) and **Total** as the sum of **Efectivo** plus **Reserva Bancaria** ($H_t^d$ in the model) for *Colombia* where the x-axis corresponds to the date and y-axis corresponds to the values of **Efectivo**, **Reserva Bancaria** and **Total**. **(3.5 points)**

### Nominal interest rate fixed by the central bank

Section *4-3 Determining the interest rate II* mentions the **federals fund rate** as the $i_t$ for the model in the USA. In Colombia $i_t$ is know as **“Tasa de intervención del Banco de la República”**.  

- Enter into the Bank of the Republic (Colombia) using the route:

**http://www.banrep.gov.co/** > Estadísticas > Tasas de interés y sector financiero > 1. Tasas de interés de política monetaria > Tasas de interés de política monetaria > Descargar y consultar: Serie diaria (desde 04/01/1999)

7. Make a plot of **Tasa de intervención de política monetaria** ($i_t$ in the model) for *Colombia* where the x-axis corresponds to the date and y-axis corresponds to the value of **Tasa de intervención de política monetaria**. **(3.5 points)**

# Goods and financial markets: The IS-LM model

## Goods market and real variables

- Enter into the World Bank's Human Development Indicators database using the link:

<**https://databank.worldbank.org/source/world-development-indicators**>

- In *Country* select *Colombia*
- In *Series* select *GDP (constant LCU)*, *Households and NPISHs Final consumption expenditure (constant LCU)*, *Gross capital formation (constant LCU)* and *General government final consumption expenditure (constant LCU)* 
- In *Time* select *VIEW RECENT YEARS: 50*
- Apply changes and download the data using *Download options > Excel* at the upper right corner of the platform

8. Make a plot of *GDP (constant LCU)* ($Y_t$ in the model expressed in real terms), *Households and NPISHs Final consumption expenditure (constant LCU)* ($C_t$ in the model expressed in real terms), *Gross capital formation (constant LCU)* ($I_t$ in the model expressed in real terms) and *General government final consumption expenditure (constant LCU)* ($G_t$ in the model expressed in real terms)  for *Colombia* where the x-axis corresponds to the date and y-axis corresponds to the values of *GDP (constant LCU)*, *Households and NPISHs Final consumption expenditure (constant LCU)*, *Gross capital formation (constant LCU)* and *General government final consumption expenditure (constant LCU)*. **(3.5 points)**

## Exercise 5

This exercises is taken from: 

**Oliver Blanchard (2017) Macroeconomics (7 Edition)** > Chapter 5 Goods and Financial Markets; The IS-LM model > Questions and Problems > Exercise 5

Consider the following numerical example of the IS-LM model:

$$C_t = 100 + 0.3Y_{tD}$$

$$I_t = 150 + 0.2Y_t - 1000i_t$$
$$T_t = 100$$
$$G_t = 200$$
$$\overline{i}_t = 0.01 (1\%)$$
$$(\frac{M}{P})^s = 1200$$
$$(\frac{M}{P})^d = 2Y_t - 4000i_t$$

9. Find the equation for aggregate demand. **(3.5 points)**

10. Derive the IS relation. **(3.5 points)**

11. Derive the LM relation assuming that the central bank fix $\overline{i}_t = 0.01 (1\%)$. **(3.5 points)**

12. Solve for the equilibrium values of $Y_t$, $i_t$, $C_t$ and $I_t$. **(3.5 points)**

13. Suppose that the central bank increases money supply to $(\frac{M}{P})^s = 1500$. What is the impact of this expansionary monetary policy on the IS and LM curves? **(3.5 points)**

14. Find the new equilibrium values of $Y_t$, $i_t$, $C_t$ and $I_t$ when $(\frac{M}{P})^s = 1500$. **(4 points)**